frase = 'Curso em Vídeo Python'
print(frase[3])
print(frase[4:13])
print(frase[:12])
print(frase[10:])
print(frase[2:15:3])
print(frase)
print(frase.count('o'))
print(frase.upper())
print(len(frase))
print(frase.replace('Python', 'Android'))
print(frase)
frase = frase.replace('Curso', 'Aula')
print(frase)
print(frase.lower().find('vídeo'))
print(frase.split())
dividido = frase.split()
print(dividido[0])
print(dividido[3])
