a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('Só tem números? ', a.isnumeric())
print('Só tem letras? ', a.isalpha())
print('Tem letras e números? ', a.isalnum())
print('Só tem letras minúsculas? ', a.islower())
print('Só tem letras maiúsculas? ', a.isupper())
print('Está capitalizada? ', a.istitle())
