from random import randint
from time import sleep
import pygame
pygame.init()
pygame.mixer.music.load('BossTheme MP3.mp3')
pygame.mixer.music.play()

print('\033[35m=\033[m'*37)
print('Sorteador de exercícios para revisão!')
print('\033[35m=\033[m'*37)
ex = int(input('\nDigite qual o último exercício estudado: '))
print('Sorteando', end=' ')
print('.', end='')
sleep(0.5)
print('.', end='')
sleep(0.5)
print('.', end='')
sleep(0.5)
print('.', end='')
sleep(0.5)
print('.')
sleep(0.8)
print('\033[35m=\033[m'*35)
print(f'O exercício para revisar hoje é {randint(1, ex)}')
print('\033[35m=\033[m'*35)
input()
